spring:
  application:
    name: query.service
  data:
    redis:
      host: localhost
      port: 6379
  spring:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: client-event-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
          spring.json.value.default.type: com.qryservice.query.service.dto.ClienteEvent

